platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest
inputs:
- name: source-code
outputs:
- name: refapp-statistics-java-release
run:
  path: refapp-statistics-java/ci/tasks/refapp-statistics/compile/task.sh
