platform: linux

image_resource:
  type: docker-image
  source:
    repository: cnsadmin/struts-example
    tag: latest
inputs:
  - name: source-code
  - name: refapp-statistics-java-release
run:
  path: refapp-statistics-java/ci/tasks/refapp-statistics/cf-push/task.sh
params:
  CF_API: ((CF_API))
  CF_API_USER: ((CF_API_USER))
  CF_API_PASSWORD: ((CF_API_PASSWORD))
  CF_ORG: ((CF_ORG))
  CF_SPACE: ((CF_SPACE))
